#!/usr/bin/env php
<?php

define('LARAVEL_START', microtime(true));

$autoloaded = false;

foreach (array(__DIR__ . '/vendor/autoload.php', __DIR__ . '/../../autoload.php') as $file) {
    if (file_exists($file)) {
        require $file;
        $autoloaded = true;
        break;
    }
}

if (!$autoloaded) {
    fwrite(STDERR,
        'You need to set up the project dependencies using Composer:' . PHP_EOL .
        '    composer install' . PHP_EOL .
        'You can learn all about Composer on https://getcomposer.org/.' . PHP_EOL
    );
    exit(1);
}

$app = require_once __DIR__.'/bootstrap/app.php';

$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);

exit($kernel->handle(new Symfony\Component\Console\Input\ArgvInput, new Symfony\Component\Console\Output\ConsoleOutput));
